const express = require('express');
const jsonParser = require('body-parser').json();
const path = require('path');

const {Locationid} = require('../models/locationModels');

const router = express.Router();
router.use(jsonParser);

// Get endpoint

router.get('/', (req,res) => {
  Locationid
    .find()
    .exec()
    .then(locations => {
      res.json({
        locations: locations.map(
          (location) => location.apiRepr()
        )
      });
    });
});

// Find location by name
// router.get('/:locationName', (req, res) => {
//   Locationid
//     .findOne({'locationName': req.params.locationName}) // use this syntax if the id is in the database, else use findById(req.params.id) = id generated by mongodb / 
//     .exec()
//     .then(location => res.json(location.apiRepr()))
//     .catch(err => {
//       console.error(err);
//         res.status(404).json({message: 'Location Name Not Found'})
//     });
// });

// POST endpoint
router.post('/', (req, res) => {
  const requiredFields = ['locationName', 'address'];
  for (let i=0; i<requiredFields.length; i++) {
    const field = requiredFields[i];
    if (!(field in req.body)) {
      const message = `Missing \`${field}\` in request body`
      console.error(message);
      return res.status(400).send(message);
    }
  }

  Locationid
    .create({
      locationName: req.body.locationName,
      address: req.body.address
    })
    .then(
      console.log(req.body.dishname)
    )
    .then(
        location => res.status(201).json(location.apiRepr())
    )
    .catch(err => {
        console.error(err);
        res.status(500).json({error: 'Something went wrong'});
    });
});


router.put('/:id', (req, res) => {
  // ensure that the id in the request path and the one in request body match
  if (!(req.params.id && req.body.id && req.params.id === req.body.id)) {
    const message = (
      `Request path id (${req.params.id}) and request body id ` +
      `(${req.body.id}) must match`);
    console.error(message);
    res.status(400).json({message: message});
  }

  // we only support a subset of fields being updateable.
  // if the user sent over any of the updatableFields, we udpate those values
  // in document
  const toUpdate = {};
  const updateableFields = ['address'];

  updateableFields.forEach(field => {
    if (field in req.body) {
      toUpdate[field] = req.body[field];
    }
  });

  Locationid
    .findByIdAndUpdate(req.params.id, {$set: toUpdate}) // find by Mongoose ID
    .exec()
    .then(
      Locationid => res.status(204).end())
    .catch(err => res.status(404).json({message: 'ID not found'}));
});

// DELETE endpoint
router.delete('/:id', (req, res) => {
  Locationid
    .findByIdAndRemove(req.params.id)
    .exec()
    .then(Locationid => res.status(204).end())
    .catch(err => res.status(404).json({message: 'ID not found'}));
});

// Search - endpoint

router.get('/:location', (req,res) => {
  if (req.params.location.length > 2) {
    const regex = new RegExp(req.params.location);
    Locationid
    .find({'locationName': regex}, (err, locations) => {
      res.json(locations)
    })
  } else {
    res.json([])
  }
});

module.exports = router;