//const express = require('express');

//mport express from 'express';
const express = require('express');
const jsonParser = require('body-parser').json();
const path = require('path');

const {MenuConnectid} = require('../models/menuConnectModels');
//import Dishid from '../models/dishModels';

const router = express.Router();
router.use(jsonParser);

// Get endpoint
router.get('/menu', (req,res) => {
  MenuConnectid
    .find()
    .exec()
    .then(menuItem => {
      res.json(menuItem);
    })
    .catch(err => {
      console.error(err);
        res.status(500).json({message: 'Internal server error - GET Connection - menu/location'})
    });
});

// POST endpoint
router.post('/menu', (req, res) => {
  const requiredFields = ['dish_id', 'location_id'];
  for (let i=0; i<requiredFields.length; i++) {
    const field = requiredFields[i];
    if (!(field in req.body)) {
      const message = `Missing \`${field}\` in request body`
      console.error(message);
      return res.status(400).send(message);
    }
  }

  MenuConnectid
    .create({
      dish_id: req.body.dish_id,
      location_id: req.body.location_id
    })
    .then(
        menuitem => res.status(201).json(menuitem)
    )
    .catch(err => {
        console.error(err);
        res.status(500).json({error: 'Something went wrong'});
    });
});

// populate

router.get('/checkMenu', (req,res) => {
  MenuConnectid
    .find()
    .populate('dishes')
    .populate('location')
    .exec()
    .then(dishByLocation => res.json(dishByLocation))
});



// Find dish by dishname
router.get('/:dishname', (req, res) => {
  Dishids
    .findOne({'dishname': req.params.dishname}) // use this syntax if the id is in the database, else use findById(req.params.id) = id generated by mongodb / 
    .exec()
    .then(dishes =>res.json(dishes))
    .catch(err => {
      console.error(err);
        res.status(404).json({message: 'Dish ID Not Found'})
    });
});




module.exports = router;